version: '3'
services:
  database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: lavaserver
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${PWD}/pgdata:/var/lib/postgresql/data/pgdata
  server:
    image: lavasoftware/amd64-lava-server:2018.11
    ports:
      - 80:80
    volumes:
      - ${PWD}/etc/lava-server/settings.conf:/etc/lava-server/settings.conf
      - ${PWD}/etc/lava-server/instance.conf:/etc/lava-server/instance.conf
    depends_on:
      - database
  dispatcher:
    image: lavasoftware/amd64-lava-dispatcher:2018.11
    environment:
    - "DISPATCHER_HOSTNAME=--hostname=dispatcher.lava.therub.org"
    - "LOGGER_URL=tcp://server:5555" # url to send logs
    - "MASTER_URL=tcp://server:5556" # url of lava master

#drue@nuc:~/lava$ docker-compose exec server lava-server manage users add --staff --superuser --email dan.rue@linaro.org --passwd foo drue
