version: '3'
services:
  database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: lavaserver
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    #image: lavasoftware/amd64-lava-server:2018.11

    # Use an updated entrypoint; this is necessary to fix a timing issue on first run,
    # and will become unnecessary once amd64-lava-server is updated to include
    # https://git.lavasoftware.org/lava/pkg/docker/commit/98fe3deecbdddfc03e99fdb8a87c379acdd1a5a6
    build:
      context: ./docker-server

    ports:
      - 80:80
    volumes:
      - ${PWD}/server/etc/lava-server/settings.conf:/etc/lava-server/settings.conf
      - ${PWD}/server/etc/lava-server/instance.conf:/etc/lava-server/instance.conf
      - ${PWD}/server/etc/lava-server/dispatcher-config/health-checks:/etc/lava-server/dispatcher-config/health-checks
      - ${PWD}/server/etc/lava-server/dispatcher-config/devices:/etc/lava-server/dispatcher-config/devices
      - ${PWD}/server/root/provision.sh:/root/provision.sh
    depends_on:
      - database
  dispatcher:
    image: lavasoftware/amd64-lava-dispatcher:2018.11
    privileged: true
    devices:
      - '/dev/kvm:/dev/kvm'
      - '/dev/net/tun:/dev/net/tun'
    environment:
      - "DISPATCHER_HOSTNAME=--hostname=dispatcher"
      - "LOGGER_URL=tcp://server:5555" # url to send logs
      - "MASTER_URL=tcp://server:5556" # url of lava master
    volumes:
      - '/boot:/boot:ro'
      - '/lib/modules:/lib/modules:ro'

  # Local health check image hosting
  images:
    image: nginx
    volumes:
      - ${PWD}/images:/usr/share/nginx/html:ro

volumes:
  pgdata:
