version: '3'
services:
  server:
    build:
      context: ./docker-server
    #image: lavasoftware/amd64-lava-server:2018.11
    ports:
      - 80:80
    volumes:
      - ${PWD}/etc/lava-server/settings.conf:/etc/lava-server/settings.conf
  dispatcher:
    image: lavasoftware/amd64-lava-dispatcher:2018.11
    environment:
    - "DISPATCHER_HOSTNAME=--hostname=dispatcher.lava.therub.org"
    - "LOGGER_URL=tcp://server:5555" # url to send logs
    - "MASTER_URL=tcp://server:5556" # url of lava master

#$ docker-compose exec server lava-server manage users add --staff --superuser --email dan.rue@linaro.org --passwd foo drue

